# links
[WEB_BULLET]
	LAUNCH_URL="www.mplayer.com/cgi-bin/mplayer-set-up.sh?distribution=393"
	DIALOG_TITLE="Play MiG Alley on Mplayer.com!"

	VENDOR_PROMO_CODE="393"
	TABLE="MPLAYNOW"
[MPLAYNOW]
	INSTALL_TYPE=RICE-MA
