/* ma_keybind.cpp — user-editable key bindings for the Linux port (H2, Sprint 88).
 *
 * WHAT THE GAME DOES. Key handling is table-driven: `keytests::Reg3dConv(FIL_3D_KEYBOARD_TABLE)`
 * loads a KeyMapping[] out of game file 0x7501 and fills
 *     KeyMap3d::mappings[scancode][shiftstate] = <action value>
 * where the action value is the `KeyVal3D` constant from the KeyName(index,NAME) list in
 * KEYMAPS.H (value == index*2). STUB3D's OnKeyInput then looks the pressed scancode up in that
 * array. So a rebind is exactly one array store — the hard part is naming things.
 *
 * WHY IT IS DONE HERE AND NOT BY EDITING THE TABLE. Reg3dConv checksums the table it loads and
 * calls EmitSysErr("Key table has changed between loads???") if two loads disagree. Overrides are
 * therefore applied AFTER the game's own load, straight into the live mappings array — the game
 * always loads its own unmodified table, and the checksum never sees our changes.
 *
 * FILE FORMAT (controls.cfg, in the game directory unless MA_CONTROLS overrides the path):
 *     # comment
 *     ELEVATOR_BACK      = 0x50          ; action = scancode          (shift state 0)
 *     ROTLEFT            = 0x4B, 1       ; action = scancode, shift   (shift state 1)
 * Names are the game's own action names, so `MA_DUMP_BINDINGS=1` writes a file that is already a
 * valid input file — see the current binding, edit the number, restart. That round-trip is the
 * whole point: nobody can guess DirectInput scancodes, but everybody can edit a line they can see.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#include "ma_keyactions.inc"

/* Provided by the caller (STUB3D) so this file needs no engine headers: a pointer to the live
   mappings array (KeyMap3d::mappings is UWord[512][8] — 2-byte cells), its dimensions, and the
   game directory. */
extern "C" void ma_keybind_apply(unsigned short* mappings, int maxkeys, int shiftstates,
                                 const char* gamedir)
{
    if (!mappings || maxkeys <= 0 || shiftstates <= 0) return;

    char path[1024];
    const char* env = getenv("MA_CONTROLS");
    if (env && *env) snprintf(path, sizeof(path), "%s", env);
    else             snprintf(path, sizeof(path), "%s/controls.cfg", gamedir ? gamedir : ".");

    /* ---- dump mode: write what is currently bound, in the format we accept back ---- */
    if (getenv("MA_DUMP_BINDINGS")) {
        FILE* f = fopen(path, "w");
        if (!f) { fprintf(stderr, "[keybind] cannot write %s\n", path); }
        else {
            fprintf(f, "# MiG Alley key bindings (native Linux port).\n"
                       "# Generated by MA_DUMP_BINDINGS=1 — this file is also a valid INPUT file:\n"
                       "# edit a scancode and restart. Format:  ACTION = <scancode>[, <shiftstate>]\n"
                       "# Scancodes are DirectInput (DIK_*) values; shiftstate 0 = unmodified.\n\n");
            int written = 0;
            for (int sc = 0; sc < maxkeys; sc++) {
                for (int sh = 0; sh < shiftstates; sh++) {
                    int v = mappings[sc * shiftstates + sh];
                    if (!v) continue;
                    const char* nm = 0;
                    for (unsigned i = 0; i < sizeof(ma_key_actions)/sizeof(ma_key_actions[0]); i++)
                        if (ma_key_actions[i].val == v) { nm = ma_key_actions[i].name; break; }
                    /* The shift state MUST be on the same line as the binding. Emitting it as a
                       following comment (as the first cut did) makes the dump non-round-trippable:
                       reloading would bind every shifted action at shift 0 and clobber whatever
                       was there. A dump that cannot be fed back is not a bindings file. */
                    if (nm) {
                        if (sh) fprintf(f, "%-28s = 0x%02X, %d\n", nm, sc, sh);
                        else    fprintf(f, "%-28s = 0x%02X\n", nm, sc);
                    } else {
                        if (sh) fprintf(f, "# unnamed action %d = 0x%02X, %d\n", v, sc, sh);
                        else    fprintf(f, "# unnamed action %d = 0x%02X\n", v, sc);
                    }
                    written++;
                }
            }
            fclose(f);
            fprintf(stderr, "[keybind] wrote %d current bindings to %s\n", written, path);
        }
    }

    /* ---- load mode: apply overrides ---- */
    FILE* f = fopen(path, "r");
    if (!f) {
        if (getenv("MA_TRACE_KEY")) fprintf(stderr, "[keybind] no %s — using the game's own table\n", path);
        return;
    }
    char line[512];
    int applied = 0, bad = 0;
    while (fgets(line, sizeof(line), f)) {
        char* p = line;
        while (*p && isspace((unsigned char)*p)) p++;
        if (!*p || *p == '#' || *p == ';') continue;
        char* eq = strchr(p, '=');
        if (!eq) continue;
        *eq = 0;
        char* name = p;
        char* end = name + strlen(name);
        while (end > name && isspace((unsigned char)end[-1])) *--end = 0;
        char* val = eq + 1;
        /* strip a trailing ; comment */
        char* semi = strchr(val, ';'); if (semi) *semi = 0;
        char* hash = strchr(val, '#'); if (hash) *hash = 0;

        int sc = -1, sh = 0;
        if (sscanf(val, " %i , %i", &sc, &sh) < 1) { bad++; continue; }

        int action = -1;
        for (unsigned i = 0; i < sizeof(ma_key_actions)/sizeof(ma_key_actions[0]); i++)
            if (!strcmp(ma_key_actions[i].name, name)) { action = ma_key_actions[i].val; break; }
        if (action < 0) {
            fprintf(stderr, "[keybind] %s: unknown action '%s' — ignored\n", path, name);
            bad++; continue;
        }
        if (sc < 0 || sc >= maxkeys || sh < 0 || sh >= shiftstates) {
            fprintf(stderr, "[keybind] %s: %s scancode 0x%X/shift %d out of range — ignored\n",
                    path, name, sc, sh);
            bad++; continue;
        }
        mappings[sc * shiftstates + sh] = (unsigned short)action;
        if (getenv("MA_TRACE_KEY"))
            fprintf(stderr, "[keybind] %s -> scancode 0x%02X shift %d (action %d)\n", name, sc, sh, action);
        applied++;
    }
    fclose(f);
    fprintf(stderr, "[keybind] %s: applied %d binding(s)%s\n", path, applied,
            bad ? " (some lines ignored — see above)" : "");
}
