#!/usr/bin/env python3
"""MA-KEYMAP-1: MiG Alley keyboard map from the game's own binding table.

Source of truth: the live KeyMap3d table the game loads from game file 0x7501
(keytests::Reg3dConv), written out by MA_DUMP_BINDINGS=1 (SRC/compat/ma_keybind.cpp) as
controls.cfg lines `ACTION = <DIK scancode>[, <shiftstate>]`. Descriptions and order come from
the KeyName(index, ACTION) /*comment*/ list in SRC/H/KEYMAPS.H.
Shift state = KeyName number of the held modifier (STUB3D.CPP: currshifts = index>>1):
0 none, 1 CapsLock (KeySrc_BN_extsh), 2 LAlt, 3 AltGr, 4 LCtrl, 5 RCtrl, 6 LShift, 7 RShift.
Only one modifier counts at a time. Usage: ma_keymap.py controls.cfg SRC/H/KEYMAPS.H > KEYMAP.md
"""
import re, sys, collections

DIK = {0x01:'Esc',0x02:'1',0x03:'2',0x04:'3',0x05:'4',0x06:'5',0x07:'6',0x08:'7',0x09:'8',0x0A:'9',
0x0B:'0',0x0C:'-',0x0D:'=',0x0E:'Backspace',0x0F:'Tab',0x10:'Q',0x11:'W',0x12:'E',0x13:'R',0x14:'T',
0x15:'Y',0x16:'U',0x17:'I',0x18:'O',0x19:'P',0x1A:'[',0x1B:']',0x1C:'Enter',0x1D:'LCtrl',0x1E:'A',
0x1F:'S',0x20:'D',0x21:'F',0x22:'G',0x23:'H',0x24:'J',0x25:'K',0x26:'L',0x27:';',0x28:"'",0x29:'`',
0x2A:'LShift',0x2B:'\\',0x2C:'Z',0x2D:'X',0x2E:'C',0x2F:'V',0x30:'B',0x31:'N',0x32:'M',0x33:',',
0x34:'.',0x35:'/',0x36:'RShift',0x37:'Num*',0x38:'LAlt',0x39:'Space',0x3A:'CapsLock',0x3B:'F1',
0x3C:'F2',0x3D:'F3',0x3E:'F4',0x3F:'F5',0x40:'F6',0x41:'F7',0x42:'F8',0x43:'F9',0x44:'F10',
0x45:'NumLock',0x46:'ScrollLock',0x47:'Num7',0x48:'Num8',0x49:'Num9',0x4A:'Num-',0x4B:'Num4',
0x4C:'Num5',0x4D:'Num6',0x4E:'Num+',0x4F:'Num1',0x50:'Num2',0x51:'Num3',0x52:'Num0',0x53:'Num.',
0x57:'F11',0x58:'F12',0x9C:'NumEnter',0x9D:'RCtrl',0xB5:'Num/',0xB7:'PrintScreen',0xB8:'AltGr',
0xC5:'Pause',0xC7:'Home',0xC8:'Up',0xC9:'PgUp',0xCB:'Left',0xCD:'Right',0xCF:'End',0xD0:'Down',
0xD1:'PgDn',0xD2:'Insert',0xD3:'Delete',0xDB:'LWin',0xDC:'RWin',0xDD:'Apps'}
STATE = {1:'CapsLock', 2:'LAlt', 3:'AltGr', 4:'LCtrl', 5:'RCtrl', 6:'LShift', 7:'RShift'}
PAIRS = ((2, 3, 'Alt'), (4, 5, 'Ctrl'), (6, 7, 'Shift'))

def mods(states):
    out, st = [], set(states)
    if 0 in st: out.append(''); st.discard(0)
    for a, b, n in PAIRS:
        if a in st and b in st: out.append(n + '+'); st -= {a, b}
    out += [STATE[s] + '+' for s in sorted(st)]
    return out

cfg = collections.OrderedDict()
for ln in open(sys.argv[1], encoding='utf-8', errors='replace'):
    m = re.match(r'^(\w+)\s*=\s*(0x[0-9A-Fa-f]+)(?:\s*,\s*(\d+))?', ln)
    if m:
        cfg.setdefault(m.group(1), collections.OrderedDict()).setdefault(int(m.group(2), 16), []).append(int(m.group(3) or 0))
# Controller inputs live above the DIK range: KEYMAPS.H Raw_A<dev>_<Fire|b<n>|hat<h><dir>> = <code>
RAW = {}
for ln in open(sys.argv[2], encoding='latin-1'):
    m = re.search(r'Raw_A(\d)_(Fire|b\d+|hat\d[NSEW]{1,2})\s*=\s*(\d+)', ln)
    if m:
        dev, what, code = m.group(1), m.group(2), int(m.group(3))
        what = 'trigger' if what == 'Fire' else ('button ' + what[1:]) if what[0] == 'b' else 'hat %s %s' % (what[3], what[4:])
        RAW.setdefault(code, 'Ctl%s %s' % (dev, what))
desc, order = {}, []
for ln in open(sys.argv[2], encoding='latin-1'):
    m = re.match(r'^(?:/\*\*/)?\s*KeyName\(\s*(\d+)\s*,\s*(\w+)\s*\)\s*(?:/\*(.*?)\*/)?', ln)
    if m and m.group(2) not in desc:
        desc[m.group(2)] = (m.group(3) or '').strip(); order.append(m.group(2))

acts = [a for a in order if a in cfg and not a.startswith('KeySrc_')] + \
       [a for a in cfg if a not in desc and not a.startswith('KeySrc_')]
n = sum(len(s) for a in acts for s in cfg[a].values())
print('# MiG Alley keyboard map\n')
print('Generated by `tools/ma_keymap.py` from the game\'s own binding table (game file 0x7501, dumped by')
print('`MA_DUMP_BINDINGS=1`) and the action list in `SRC/H/KEYMAPS.H`. %d actions, %d key+modifier bindings.' % (len(acts), n))
print('Program data, not documentation: where a manual disagrees, this wins.\n')
print('**Controller inputs.** `Ctl<n>` is controller input set n (KEYMAPS.H `Raw_A<n>_*`: trigger, buttons, three')
print('8-way hats); which physical device each set is depends on Preferences → Controls.\n')
print('**Modifiers.** One at a time: CapsLock, Left Alt, AltGr, Left/Right Ctrl, Left/Right Shift. "Alt+" means')
print('either Alt key, "Ctrl+"/"Shift+" either side; a side-specific name means only that key works.\n')
print('**Linux port keys** (`SRC/compat/bob_video.cpp`, ahead of the table): Ctrl+Esc saves preferences and quits.')
print('In flight, `D` and Shift+D toggle the padlock box and Alt+D the telemetry readout; the engine never sees D.')
print('On the 2D map: arrows/WASD pan, +/-/PgUp/PgDn zoom, Esc leaves the map, F/Enter flies.\n')
print('| Keys | Action | Description |\n|---|---|---|')
for a in acts:
    keys = []
    for sc, states in cfg[a].items():
        keys += [m + DIK.get(sc, RAW.get(sc, '0x%02X' % sc)) for m in mods(states)]
    d = desc.get(a, '')
    if a == 'BOXTARGET': d = (d + ' — *Linux port: D is taken by the padlock box, see above*').strip(' —')
    print('| %s | `%s` | %s |' % (', '.join(keys).replace('|', '\\|'), a, d.replace('|', '\\|')))
print('\n## Actions in KEYMAPS.H with no key in the table\n')
print(', '.join('`%s`' % a for a in order if a not in cfg and not a.startswith(('KeySrc_', 'Reserved'))))
